spring.application.name=stocktracker
spring.datasource.url=jdbc:postgresql://localhost:5432/stocktracker
spring.datasource.username=postgres
spring.datasource.password=melnic2003
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
